MHDecora.Admin/Controllers/BannerController.cs
using MHDecora.Admin.Application.Interfaces;
using MHDecora.Admin.Domain.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MHDecora.Admin.Controllers
{
    [Authorize]
    public class BannerController : Controller
    {
        private readonly IBannerService _bannerService;

        public BannerController(IBannerService bannerService)
        {
            _bannerService = bannerService;
        }

        public async Task<IActionResult> Index()
        {
            var banners = await _bannerService.GetBanners();

            return View(banners);
        }

        [HttpPost]
        public async Task<IActionResult> Criar(Banner banner, IFormFile imagem)
        {
            await _bannerService.Criar(banner, imagem);

            Alert("Sucesso!", "O Banner foi cadastrado.", "success");

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Adicionar(Banner banner, IFormFile arquivo)
        {
            await _bannerService.Criar(banner, arquivo);

            Alert("Sucesso!", "O Banner foi cadastrado.", "success");

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Adicionar()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Excluir(int bannerId)
        {
            bool result = await _bannerService.Excluir(bannerId);

            if (result)
            {
                Alert("Sucesso!", "O Banner foi excluído.", "success");
            }
            else
            {
                Alert("Erro!", "Não foi possível excluir o banner, contate a equipe de suporte.", "danger");
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Editar(int bannerId)
        {
            var banner = await _bannerService.GetBannerById(bannerId);

            return View(banner);
        }

        [HttpPost]
        public async Task<IActionResult> Editar(IFormFile arquivo, Banner banner)
        {
            var result = await _bannerService.Editar(arquivo, banner);

            if (result)
            {
                Alert("Sucesso!", "O Banner foi editado.", "success");
            }
            else
            {
                Alert("Erro!", "Não foi possível editar o banner, contate a equipe de suporte.", "danger");
            }

            return RedirectToAction("Index");
        }

        private void Alert(string titulo, string mensagem, string alerta)
        {
            TempData["Titulo"] = titulo;
            TempData["Mensagem"] = mensagem;
            TempData["TipoAlerta"] = alerta;
        }
    }
}

MHDecora.Admin/Controllers/CategoriaController.cs
using Azure;
using MHDecora.Admin.Application.Interfaces;
using MHDecora.Admin.Domain.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace MHDecora.Admin.Controllers
{
    [Authorize]
    public class CategoriaController : Controller
    {
        private readonly ICategoriaService _categoriaService;

        public CategoriaController(ICategoriaService categoriaService)
        {
            _categoriaService = categoriaService;
        }

        public async Task<IActionResult> Index()
        {
            var categorias = await _categoriaService.GetCategorias();

            return View(categorias);
        }

        [HttpPost]
        public async Task<IActionResult> Salvar(Categoria categoria, IFormFile imagem)
        {
            var response = await _categoriaService.Criar(categoria, imagem);

            if (response)
            {
                Alert("Sucesso!", "A Categoria foi cadastrada.", "success");

            }
            else
            {
                Alert("Erro!", "Não foi possível criar a categoria, contate a equipe de suporte.", "danger");

            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Editar(int id)
        {
            var categoria = await _categoriaService.GetCategoriaById(id);

            return View(categoria);
        }

        [HttpPost]
        public async Task<IActionResult> Editar(IFormFile arquivo, Categoria categoria)
        {
            var response = await _categoriaService.Editar(categoria, arquivo);

            if (response)
            {
                Alert("Sucesso!", "A Categoria foi editada.", "success");
            }
            else
            {
                Alert("Erro!", "Não foi possível criar esta categoria, contate a equipe de suporte.", "danger");
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Excluir(int categoriaId)
        {
            bool result = await _categoriaService.Excluir(categoriaId);

            if (result)
            {
                Alert("Sucesso!", "A categoria foi excluída.", "success");
            }
            else
            {
                Alert("Erro!", "Não foi possível excluir a categoria, contate a equipe de suporte.", "danger");
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Adicionar()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Adicionar(Categoria categoria, IFormFile arquivo)
        {
            var response = await _categoriaService.Criar(categoria, arquivo);

            if (response)
            {
                Alert("Sucesso!", "A Categoria foi cadastrada.", "success");
            }
            else
            {
                Alert("Erro!", "Não foi possível criar esta categoria, contate a equipe de suporte.", "danger");
            }

            return RedirectToAction("Index");
        }

        private void Alert(string titulo, string mensagem, string alerta)
        {
            TempData["Titulo"] = titulo;
            TempData["Mensagem"] = mensagem;
            TempData["TipoAlerta"] = alerta;
        }
    }
}

MHDecora.Admin/Controllers/ConfiguracaoController.cs
using MHDecora.Admin.Domain.Entities;
using Microsoft.AspNetCore.Mvc;

namespace MHDecora.Admin.Controllers
{
    public class ConfiguracaoController : Controller
    {
        public async Task<IActionResult> Index()
        {
            return View();
        }


        [HttpGet]
        public async Task<IActionResult> Categoria()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Tag()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> SalvarCategoria(Categoria categoria)
        {

            return View();
        }

    }
}

MHDecora.Admin/Controllers/TagController.cs
using Azure;
using MHDecora.Admin.Application.Interfaces;
using MHDecora.Admin.Domain.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace MHDecora.Admin.Controllers
{
    [Authorize]
    public class TagController : Controller
    {
        private readonly ITagService _tagService;

        public TagController(ITagService tagService)
        {
            _tagService = tagService;
        }

        public async Task<IActionResult> Index()
        {
            var tags = await _tagService.GetTags();

            return View(tags);
        }

        [HttpGet]
        public async Task<IActionResult> Adicionar()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Adicionar(Tag tag)
        {
            var response = await _tagService.Criar(tag);

            if (response)
            {
                Alert("Sucesso!", "A Tag foi cadastrada.", "success");
            }
            else
            {
                Alert("Erro!", "Não foi possível criar a tag, contate a equipe de suporte.", "danger");
            }

            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Editar(int id)
        {
            var tag = await _tagService.GetTagById(id);

            return View(tag);
        }

        [HttpPost]
        public async Task<IActionResult> Editar(Tag tag)
        {
            var response = await _tagService.Editar(tag);

            if (response)
            {
                Alert("Sucesso!", "A Tag foi editada.", "success");
            }
            else
            {
                Alert("Erro!", "Não foi possível editar esta tag, contate a equipe de suporte.", "danger");
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Excluir(int tagId)
        {
            bool result = await _tagService.Excluir(tagId);

            if (result)
            {
                Alert("Sucesso!", "A tag foi excluída.", "success");
            }
            else
            {
                Alert("Erro!", "Não foi possível excluir a tag, contate a equipe de suporte.", "danger");
            }

            return RedirectToAction("Index");
        }

        private void Alert(string titulo, string mensagem, string alerta)
        {
            TempData["Titulo"] = titulo;
            TempData["Mensagem"] = mensagem;
            TempData["TipoAlerta"] = alerta;
        }
    }
}

MHDecora.Admin/Views/Configuracao/Categoria.cshtml
@model List<MHDecora.Admin.Domain.Entities.Categoria>

@{
    ViewBag.Title = "Banners";
    string titulo = TempData["Titulo"] as string;
    string mensagem = TempData["Mensagem"] as string;
    string tipoAlerta = TempData["TipoAlerta"] as string;
}

@if (!string.IsNullOrEmpty(mensagem))
{
    <div id="autoCloseAlert" class="alert alert-@tipoAlerta alert-dismissible fade show" role="alert">
        <strong>@titulo</strong> @mensagem
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
    </div>
}

<div id="msgAlert"></div>

<!-- Products Inventory -->
<div class="card card-default">
    <div class="card-header">
        <h2>Categorias</h2>

        <a data-toggle="modal" data-target="#modalAdicionar" id="adicionarCategoria" href="#" class="btn btn-primary">
            <i class="mdi mdi-plus mr-1"></i> Adicionar
        </a>

    </div>
    <div class="card-body">
        <div class="collapse" id="collapse-data-tables">
            <pre class="language-html mb-4">

                </pre>
        </div>
        <table id="productsTable" class="table table-hover table-product" style="width:100%">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Nome da Categoria</th>                    
                    <th></th>
                </tr>
            </thead>
            <tbody>

                @{
                    if (Model != null)
                    {
                        foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.Id</td>
                                <td>@item.Nome</td>
                                <td>
                                    <div class="dropdown">
                                        <a class="dropdown-toggle icon-burger-mini" href="#" role="button" id="dropdownMenuLink"
                                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" data-display="static">
                                        </a>

                                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuLink">
                                            <a class="dropdown-item" href="@Url.Action("Editar", "Banner", new { bannerId = @item.Id })">Editar</a>
                                            <a class="dropdown-item" data-toggle="modal" data-target="#modalApagar" data-id="@item.Id" id="excluirBanner" href="#">Excluir</a>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        }
                    }
                }

            </tbody>
        </table>

    </div>
</div>

@* Apagar *@
<div class="modal fade" id="modalApagar" tabindex="-1" role="dialog" aria-labelledby="modalApagarLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        @using (Html.BeginForm("Excluir", "Banner", FormMethod.Post, new { enctype = "multipart/form-data", id = "formAdicionar" }))
        {
            <input type="hidden" value="" id="bannerId" name="bannerId">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="modalApagarLabel">Confirmar Exclusão</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">
                    Tem certeza que deseja excluir este banner?
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-danger" id="confirmarExclusao">Sim</button>
                    <button type="button" class="btn btn-light" data-dismiss="modal">Não</button>
                </div>
            </div>
        }
    </div>
</div>

@* Adicionar *@
<div class="modal fade" id="modalApagar" tabindex="-1" role="dialog" aria-labelledby="modalApagarLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        @using (Html.BeginForm("SalvarCategoria", "Categoria", FormMethod.Post, new { enctype = "multipart/form-data", id = "formAdicionar" }))
        {
            <input type="hidden" value="" id="bannerId" name="bannerId">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="modalApagarLabel">Confirmar Exclusão</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label for="categoria">Categoria</label>
                        <input type="text" class="form-control" id="categoria" placeholder="Digite o nome da categoria">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-danger" id="sim">Sim</button>
                    <button type="button" class="btn btn-light" data-dismiss="modal">Não</button>
                </div>
            </div>
        }
    </div>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            var bannerId;

            $('#modalApagar').on('show.bs.modal', function (event) {
                var button = $(event.relatedTarget); // Botão que abriu o modal
                var banner = button.data('id'); // Extrair informação dos atributos data-*
                $("#bannerId").val(banner);
            });
        });
    </script>
}

MHDecora.Admin/Views/Configuracao/Tag.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}