MHDecora.Admin/Controllers/QuemSomosController.cs
using MHDecora.Admin.Application.Interfaces;
using MHDecora.Admin.Domain.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.FlowAnalysis;
using static System.Net.Mime.MediaTypeNames;

namespace MHDecora.Admin.Controllers
{
    [Authorize]
    public class QuemSomosController : Controller
    {
        private readonly IQuemSomosService _quemSomosService;

        public QuemSomosController(IQuemSomosService quemSomosService, IWebHostEnvironment webHostEnvironment)
        {
            _quemSomosService = quemSomosService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var response = await _quemSomosService.GetDados();

            if (response == null)
            {
                Alert("Erro!", "Não foi possível carregar os dados, contate a equipe de suporte.", "danger");

                return View();
            }

            return View(response);
        }

        [HttpPost]
        public async Task<IActionResult> Salvar(QuemSomos dados, IFormFile imagem)
        {
            await _quemSomosService.Salvar(dados, imagem);

            Alert("Sucesso!", "Seção Quem Somos foi atualizada.", "success");

            return RedirectToAction("Index");
        }

        private void Alert(string titulo, string mensagem, string alerta)
        {
            TempData["Titulo"] = titulo;
            TempData["Mensagem"] = mensagem;
            TempData["TipoAlerta"] = alerta;
        }
    }
}

MHDecora.Admin/Views/QuemSomos/Index.cshtml
@model MHDecora.Admin.Domain.Entities.QuemSomos

@{
    ViewBag.Title = "Adicionar Seção Quem Somos";
    string titulo = TempData["Titulo"] as string;
    string mensagem = TempData["Mensagem"] as string;
    string tipoAlerta = TempData["TipoAlerta"] as string;
}

@if (!string.IsNullOrEmpty(mensagem))
{
    <div id="autoCloseAlert" class="alert alert-@tipoAlerta alert-dismissible fade show" role="alert">
        <strong>@titulo</strong> @mensagem
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
    </div>
}

<div id="msgAlert"></div>

<div class="row">
    <div class="col-xl-12">
        <!-- Basic Examples -->
        <div class="card card-default">
            <div class="card-header">
                <h2>Adicionar Quem Somos</h2>
            </div>
            <div class="card-body">

                @using (Html.BeginForm("Salvar", "QuemSomos", FormMethod.Post, new { enctype = "multipart/form-data", id = "formSalvar" }))
                {
                    <input hidden="hidden" id="Id" name="Id" value="@Model.Id">

                    <div class="row">
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label for="fname">Título</label>
                                <input name="titulo" class="form-control" placeholder="Título" id="titulo" value="@Model?.Titulo">
                            </div>
                        </div>                        
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label for="exampleFormControlFile1">Selecione o Arquivo</label>
                                <input type="file" name="imagem" class="form-control-file" id="fileInput" accept="image/*">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-4 mb-2">
                            <div class="form-group">
                                <label for="fname" id="lblImagem1">Imagem</label>
                                <img id="previewImage1" src="@Model.CaminhoImagem" class="img-fluid" alt="Imagem do Banner" />
                            </div>                 
                        </div>
                    </div>
                    
                   <input hidden="hidden" id="descricao" name="descricao" />

                    <label for="fname">Descrição</label>                           
                    <div id="toolbar">
                        <span class="ql-formats">
                            <select class="ql-font"></select>
                            <select class="ql-size"></select>
                        </span>
                        <span class="ql-formats">
                            <button class="ql-bold"></button>
                            <button class="ql-italic"></button>
                            <button class="ql-underline"></button>
                        </span>
                        <span class="ql-formats">
                            <select class="ql-color"></select>
                        </span>
                        <span class="ql-formats">
                            <button class="ql-blockquote"></button>
                        </span>
                        <span class="ql-formats">
                            <button class="ql-list" value="ordered"></button>
                            <button class="ql-list" value="bullet"></button>
                            <button class="ql-indent" value="-1"></button>
                            <button class="ql-indent" value="+1"></button>
                        </span>
                        <span class="ql-formats">
                            <button class="ql-direction" value="rtl"></button>
                            <select class="ql-align"></select>
                        </span>
                    </div>
                    <div id="editor" class="mb-5"></div>

                    <div class="form-footer pt-5 border-top d-flex justify-content-between">
                        @*                         <a href="@Url.Action("Index", "QuemSomos")" class="btn btn-primary text-left">
                            <i class="mdi mdi-undo mr-1"></i> Voltar
                        </a> *@
                        <div>
                            <button type="submit" class="btn btn-success">Salvar</button>
                            <button type="button" class="btn btn-light ml-2" onclick="cancelar()">Cancelar</button>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
       

        $(document).ready(function () {

            var descr = '@Html.Raw(Model?.Descricao)';

            
            if (descr != null) {

                document.querySelector('.ql-editor').innerHTML = descr;
            }
           

            $('#formSalvar').submit(function (e) {
                e.preventDefault(); // Evita o envio padrão do formulário

                // Seleciona a div com a classe ql-editor
                var editor = document.querySelector('.ql-editor').innerHTML;

                var preview = document.getElementById('previewImage1');

                var descricao = $("#titulo").val();
                var fileInput = $("#fileInput").val();

                if (!descricao || editor == "<p><br></p>" || (!fileInput && (!preview.src || preview.src === ""))) {
                    Alert("Atenção!", "Verifique os campos se estão preenchidos.", "warning");
                    return;
                }

                // Obtém o texto digitado dentro do editor e atribui a variavel que está oculta
                document.getElementById('descricao').value = editor;

                // Se todos os campos estiverem preenchidos, envie o formulário
                this.submit(); // Aqui corrigimos para enviar o formulário corretamente
            });
        });
     
        // Função para exibir a visualização da imagem quando um arquivo é selecionado
        function cancelar() {
            $("#descricao").val("");
            $("#titulo").val("");

            $('#fileInput').wrap('<form>').closest('form').get(0).reset();
            $('#fileInput').unwrap();

            var label = document.getElementById('labelImage1');
            var preview = document.getElementById('previewImage1');

            preview.src = '';
            preview.style.display = 'none';
            label.style.display = 'none';
        }

        // Função para exibir a visualização da imagem quando um arquivo é selecionado
        function previewFile() {
           
            var label = document.getElementById('lblImagem1');
            var preview = document.getElementById('previewImage1');
            var fileInput = document.getElementById('fileInput').files[0];
            var reader = new FileReader();


            reader.onloadend = function () {
                //$("#imagem").attr('display', 'inline-block');
                preview.src = reader.result;
                preview.style.display = 'block';
                label.style.display = 'block';
            }

            if (fileInput) {
                reader.readAsDataURL(fileInput);
            } else {
                preview.src = '';
                preview.style.display = 'none';
            }
        }

        // Adiciona um listener de mudança no campo de entrada do arquivo
        document.getElementById('fileInput').addEventListener('change', previewFile);
    </script>

}