MHDecora.Admin/Controllers/MontagemController.cs
using MHDecora.Admin.Application.Interfaces;
using MHDecora.Admin.Application.Services;
using MHDecora.Admin.Domain.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections;

namespace MHDecora.Admin.Controllers
{
    [Authorize]
    public class MontagemController : Controller
    {
        private readonly ITagService _tagService;
        private readonly IMontagemService _montagemService;
        private readonly ICategoriaService _categoriaService;
        private readonly ITemaService _temaService;

        public MontagemController(IMontagemService montagemService, ICategoriaService categoriaService, ITagService tagService, ITemaService temaService)
        {
            _montagemService = montagemService;
            _categoriaService = categoriaService;
            _tagService = tagService;
            _temaService = temaService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var response = await _montagemService.Buscar();

            if (response == null)
            {
                Alert("Erro!", "Não foi possível carregar os dados, contate a equipe de suporte.", "danger");

                return View(response);
            }

            return View(response);
        }

        [HttpGet]
        public async Task<IActionResult> Adicionar()
        {
            //var categorias = await _categoriaService.GetCategorias();

            var listaCategoria = await _categoriaService.GetCategorias();

            //ViewBag.Tags = await _tagService.GetTags();
            ViewBag.Categorias = new SelectList(listaCategoria, "Id", "Nome");

            var listaTemas = await _temaService.Buscar();

            ViewBag.Temas = new SelectList(listaTemas, "Id", "Titulo");

            return View(new Montagem());
        }

        [HttpPost]
        public async Task<IActionResult> Salvar(Montagem montagem, IFormFile arquivo1, IFormFile arquivo2, IFormFile arquivo3, IFormFile arquivo4, List<string> tag)
        {

            //atribuindo Texto Imagem para o Nome correto da Categoria
            var categoria = await _categoriaService.GetCategoriaById(montagem.CategoriaId);
            var categoriaNome = categoria.Nome;
            montagem.TextoImagem = categoriaNome;

            var response = await _montagemService.Salvar(montagem, arquivo1, arquivo2, arquivo3, arquivo4, tag);

            if (response)
            {
                Alert("Sucesso!", "A Montagem foi cadastrada.", "success");
            }
            else
            {
                Alert("Erro!", "Não foi possível criar esta montagem, contate a equipe de suporte.", "danger");
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Excluir(int montagemId)
        {
            bool result = await _montagemService.Excluir(montagemId);

            if (result)
            {
                Alert("Sucesso!", "A montagem foi excluída.", "success");
            }
            else
            {
                Alert("Erro!", "Não foi possível excluir a montagem, contate a equipe de suporte.", "danger");
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Editar(int id)
        {
            var response = await _montagemService.GetById(id);

            var listaCategoria = await _categoriaService.GetCategorias();

            var listaTemas = await _temaService.Buscar();
                   
            var listaTags = await _tagService.GetTags();
            
            ViewBag.Tags = new SelectList(listaTags, "Id", "Nome");
            ViewBag.Categorias = new SelectList(listaCategoria, "Id", "Nome");
            ViewBag.Temas = new SelectList(listaTemas, "Id", "Titulo");
               
            return View(response);
        }

        [HttpPost]
        public async Task<IActionResult> Editar(Montagem montagem, IFormFile arquivo1, IFormFile arquivo2, IFormFile arquivo3, IFormFile arquivo4, List<string> tag)
        {

            //buscar nome categoria
            var categoria = await _categoriaService.GetCategoriaById(montagem.CategoriaId);
            var categoriaNome = categoria.Nome;
            montagem.TextoImagem = categoriaNome;

            var response = await _montagemService.Editar(montagem, arquivo1, arquivo2, arquivo3, arquivo4, tag);

            if (response)
            {
                Alert("Sucesso!", "A montagem foi editada.", "success");
            }
            else
            {
                Alert("Erro!", "Não foi possível editar a montagem, contate a equipe de suporte.", "danger");
            }

            return RedirectToAction("Index");
        }

        private void Alert(string titulo, string mensagem, string alerta)
        {
            TempData["Titulo"] = titulo;
            TempData["Mensagem"] = mensagem;
            TempData["TipoAlerta"] = alerta;
        }
    }
}

MHDecora.Admin/Views/Montagem/Index.cshtml
@model List<MHDecora.Admin.Domain.Entities.Montagem>

@{
    ViewBag.Title = "Banners";
    string titulo = TempData["Titulo"] as string;
    string mensagem = TempData["Mensagem"] as string;
    string tipoAlerta = TempData["TipoAlerta"] as string;
}



<style>
    #productsTable {
        max-width: 100%; /* Defina o tamanho máximo do contêiner conforme necessário */
        /* overflow: hidden; */ /* Oculta barras de rolagem se houver conteúdo excedente */
    }

        #productsTable table {
            width: 100%; /* Ajusta a largura da tabela para preencher o contêiner */
        }

    .dataTables_scrollBody {
        overflow: visible !important;
    }
</style>

@if (!string.IsNullOrEmpty(mensagem))
{
    <div id="autoCloseAlert" class="alert alert-@tipoAlerta alert-dismissible fade show" role="alert">
        <strong>@titulo</strong> @mensagem
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
    </div>
}

<div id="msgAlert"></div>

<!-- Products Inventory -->

@* <link id="main-css-href" rel="stylesheet" href="~/css/style.css" />
<script src="~/plugins/nprogress/nprogress.js"></script> *@

<div class="card card-default">
    <div class="card-header">
        <h2>Montagens</h2>


        <a href="@Url.Action("Adicionar", "Montagem")" class="btn btn-primary">
            <i class="mdi mdi-plus mr-1"></i> Adicionar
        </a>

    </div>
    <div class="card-body">
        <div class="collapse" id="collapse-data-tables">
            <pre class="language-html mb-4">

                </pre>
        </div>
        <table id="productsTable" class="table table-hover table-product" style="width:100%">
            <thead>
                <tr>
                    <th>Imagem</th>
                    <th>Categoria</th>
                    <th>Destaque</th>
                    <th>Titulo</th>
                    <th>Nome</th>
                    @* <th>Texto</th> *@
                    <th>Opções</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>

                @{
                    if (Model.Count > 0)
                    {
                        foreach (var item in Model)
                        {
                            <tr>
                                <td class="py-0">
                                    <img src="@item.CaminhoImagem" style="margin-top: 8px;max-width: 85px;" alt="Product Image">
                                </td>
                                <td>@item.Categoria.Nome</td>
                                @if (@item.MontagemDestaque)
                                {
                                    <td>SIM</td>
                                }
                                else
                                {
                                    <td>NÃO</td>
                                }
                                <td>@item.Titulo</td>
                                <td>@item.TextoImagem</td>
                                @*<td>@item.Texto</td>*@
                                @*<td>@item.LinkBotao</td>*@
                                <td>
                                    <div class="dropdown">
                                        <a class="dropdown-toggle icon-burger-mini" href="#" role="button" id="dropdownMenuLink"
                                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" data-display="static">
                                        </a>

                                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuLink">
                                            <a class="dropdown-item" href="@Url.Action("Editar", "Montagem", new { Id = @item.Id })">Editar</a>
                                            <a class="dropdown-item" data-toggle="modal" data-target="#modalApagar" onclick="setaID(@item.Id)" id="excluirMontagem" href="#">Excluir</a>
                                        </div>
                                    </div>
                                </td>
                                <td></td>
                            </tr>
                        }
                    }
                }

            </tbody>
        </table>

    </div>
</div>

@* <script src="~/plugins/jquery/jquery.min.js"></script>
<script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js"></script> *@

@* <script src="~/plugins/datatables/datatables-1.10.18/js/jquery.datatables.min.js"></script> 
<script src="~/js/custom.js"></script> *@

@* Apagar *@
<div class="modal fade" id="modalApagar" tabindex="-1" role="dialog" aria-labelledby="modalApagarLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        @using (Html.BeginForm("Excluir", "Montagem", FormMethod.Post, new { enctype = "multipart/form-data", id = "formExcluir" }))
        {
            <input type="hidden" value="" id="montagemId" name="montagemId">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="modalApagarLabel">Confirmar Exclusão</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">
                    Tem certeza que deseja excluir esta montagem?
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-danger" id="confirmarExclusao">Sim</button>
                    <button type="button" class="btn btn-light" data-dismiss="modal">Não</button>
                </div>
            </div>
        }
    </div>
</div>



@section Scripts {

    <script>
        function setaID(id) {
            $('#montagemId').val(id);
        }
    </script>
}