MHDecora.Admin/Controllers/TemaController.cs
using Azure;
using MHDecora.Admin.Application.Interfaces;
using MHDecora.Admin.Application.Services;
using MHDecora.Admin.Domain.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace MHDecora.Admin.Controllers
{
    [Authorize]
    public class TemaController : Controller
    {
        private readonly ITagService _tagService;
        private readonly ITemaService _temaService;

        public TemaController(ITemaService temaService, ITagService tagService)
        {
            _temaService = temaService;
            _tagService = tagService;
        }

        public async Task<IActionResult> Index()
        {
            var response = await _temaService.Buscar();                     
                      
            if (response == null)
            {                
                return View(response);
            }

            return View(response);
        }

        [HttpGet]
        public async Task<IActionResult> Adicionar()
        {
            ViewBag.Tags = await _tagService.GetTags();

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Adicionar(Tema tema, IFormFile arquivo, List<string> tag)
        {
            var response = await _temaService.Salvar(tema, arquivo, tag);

            if (response)
            {
                Alert("Sucesso!", "O Tema foi cadastrado.", "success");
            }
            else
            {
                Alert("Erro!", "Não foi possível criar este tema, contate a equipe de suporte.", "danger");
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Excluir(int temaId)
        {
            bool result = await _temaService.Excluir(temaId);

            if (result)
            {
                Alert("Sucesso!", "O Tema foi excluído.", "success");
            }
            else
            {
                Alert("Erro!", "Não foi possível excluir o tema, contate a equipe de suporte.", "danger");
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Editar(int id)
        {
            var tema = await _temaService.BuscarPorId(id);

            //var listaTags = await _tagService.GetTags();

            //ViewBag.Tags = new SelectList(listaTags, "Id", "Nome");

            return View(tema);
        }

        [HttpPost]
        public async Task<IActionResult> Editar(IFormFile arquivo, Tema tema, List<string> tag)
        {
            var result = await _temaService.Editar(arquivo, tema, tag);

            if (result)
            {
                Alert("Sucesso!", "O Tema foi editado.", "success");
            }
            else
            {
                Alert("Erro!", "Não foi possível editar o tema, contate a equipe de suporte.", "danger");
            }

            return RedirectToAction("Index");
        }

        private void Alert(string titulo, string mensagem, string alerta)
        {
            TempData["Titulo"] = titulo;
            TempData["Mensagem"] = mensagem;
            TempData["TipoAlerta"] = alerta;
        }
    }
}

MHDecora.Admin/Views/Tema/Adicionar.cshtml
@* @model List<MHDecora.Admin.Domain.Entities.Tag> *@

@{
    ViewBag.Title = "Adicionar Tema";
    string titulo = TempData["Titulo"] as string;
    string mensagem = TempData["Mensagem"] as string;
    string tipoAlerta = TempData["TipoAlerta"] as string;
}

@if (!string.IsNullOrEmpty(mensagem))
{
    <div id="autoCloseAlert" class="alert alert-@tipoAlerta alert-dismissible fade show" role="alert">
        <strong>@titulo</strong> @mensagem
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
    </div>
}

<div id="msgAlert"></div>

<div class="row">

    <div class="col-xl-12">
        <!-- Basic Examples -->
        <div class="card card-default">
            <div class="card-header">
                <h2>Adicionar Tema</h2>
            </div>
            <div class="card-body">

                @using (Html.BeginForm("Adicionar", "Tema", FormMethod.Post, new { enctype = "multipart/form-data", id = "formAdicionar" }))
                {
                    <div class="row">
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label for="fname">Título</label>
                                <input name="titulo" class="form-control" placeholder="Título da sessão" id="titulo">
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label for="fname">Descrição</label>
                                <input name="texto" class="form-control" placeholder="Descrição da imagem" id="texto">
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label for="exampleFormControlFile1">Selecione o Arquivo</label>
                                <input type="file" name="arquivo" class="form-control-file" id="fileInput" accept="image/*">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-4 mb-2">
                            <div class="form-group">
                                <label id="labelImage" for="fname" style="display:none">Imagem</label>
                                <img id="previewImage" src="#" class="img-fluid" alt="Imagem do Banner" style="display:none" />
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12 mb-5">
                            <label id="labelImage5" for="fname">Digite as Tags</label>
                            <textarea class="form-control" id="tags" name="tags" data-placeholder="Digite as tag para ser encontrado nas buscas" rows="5"></textarea>

                            @* <select class="form-select" name="tag" id="tag" data-placeholder="Digite a tag" multiple>
                                <option value="">-- Escolha as tags --</option>
                                @if (@ViewBag.Tags != null)
                                {
                                    @for (int i = 0; i < @ViewBag.Tags.Count; i++)
                                    {
                                        <option value="@ViewBag.Tags[i].Id">@ViewBag.Tags[i].Nome</option>
                                    }
                                }
                            </select> *@
                        </div>
                    </div>
                    <div class="form-footer pt-5 border-top d-flex justify-content-between">
                        <a href="@Url.Action("Index", "Tema")" class="btn btn-primary text-left">
                            <i class="mdi mdi-undo mr-1"></i> Voltar
                        </a>
                        <div>
                            <button type="submit" class="btn btn-success">Salvar</button>
                            <button type="button" class="btn btn-light ml-2" onclick="cancelar()">Cancelar</button>
                        </div>
                    </div>
                }

            </div>
        </div>


    </div>

</div>
@section Scripts {

    <script>


        $(document).ready(function () {
            // $('#tag').select2({
            //     theme: "bootstrap-5",
            //     width: $(this).data('width') ? $(this).data('width') : $(this).hasClass('w-100') ? '100%' : 'style',
            //     placeholder: $(this).data('placeholder'),
            //     closeOnSelect: false,
            // });

            $('#formAdicionar').submit(function (e) {
                e.preventDefault(); // Evita o envio padrão do formulário

                var descricao = $("#texto").val();
                var titulo = $("#titulo").val();
                var fileInput = $("#fileInput").val();
                var tags = $("#tags").val();

                if (!descricao || !titulo || !fileInput || !tags) {
                    Alert("Atenção!", "Verifique os campos se estão preenchidos.", "warning");
                    return;
                }

                // Se todos os campos estiverem preenchidos, envie o formulário
                this.submit(); // Aqui corrigimos para enviar o formulário corretamente
            });
        });

        // Função para exibir a visualização da imagem quando um arquivo é selecionado
        function cancelar() {
            $("#texto").val("");
            $("#titulo").val("");
            $("#tags").val("");

            $('#fileInput').wrap('<form>').closest('form').get(0).reset();
            $('#fileInput').unwrap();

            var label = document.getElementById('labelImage');
            var preview = document.getElementById('previewImage');

            preview.src = '';
            preview.style.display = 'none';
            label.style.display = 'none';
        }

        // Função para exibir a visualização da imagem quando um arquivo é selecionado
        function previewFile() {
            var label = document.getElementById('labelImage');
            var preview = document.getElementById('previewImage');
            var fileInput = document.getElementById('fileInput').files[0];
            var reader = new FileReader();

            reader.onloadend = function () {
                //$("#imagem").attr('display', 'inline-block');
                preview.src = reader.result;
                preview.style.display = 'block';
                label.style.display = 'block';
            }

            if (fileInput) {
                reader.readAsDataURL(fileInput);
            } else {
                preview.src = '';
                preview.style.display = 'none';
            }
        }

        // Adiciona um listener de mudança no campo de entrada do arquivo
        document.getElementById('fileInput').addEventListener('change', previewFile);
    </script>

}

MHDecora.Admin/Views/Tema/Editar.cshtml
@model MHDecora.Admin.Domain.Entities.Tema

@{
    ViewBag.Title = "Editar Tema";
    string titulo = TempData["Titulo"] as string;
    string mensagem = TempData["Mensagem"] as string;
    string tipoAlerta = TempData["TipoAlerta"] as string;
}

@if (!string.IsNullOrEmpty(mensagem))
{
    <div id="autoCloseAlert" class="alert alert-@tipoAlerta alert-dismissible fade show" role="alert">
        <strong>@titulo</strong> @mensagem
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
    </div>
}

<div id="msgAlert"></div>

<div class="row">
    <div class="col-xl-12">
        <!-- Basic Examples -->
        <div class="card card-default">
            <div class="card-header">
                <h2>Adicionar Tema</h2>
            </div>
            <div class="card-body">
                @using (Html.BeginForm("Editar", "Tema", FormMethod.Post, new { enctype = "multipart/form-data", id = "formEditar" }))
                {
                    <input hidden="hidden" id="Id" name="Id" value="@Model.Id">
                    <div class="row">
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label for="titulo">Título</label>
                                <input name="titulo" class="form-control" placeholder="Título da sessão" id="titulo" value="@Model.Titulo">
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label for="texto">Descrição</label>
                                <input name="texto" class="form-control" placeholder="Descrição da imagem" id="texto" value="@Model.Texto">
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label for="fileInput">Selecione o Arquivo</label>
                                <input type="file" name="arquivo" class="form-control-file" id="fileInput" accept="image/*">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-4 mb-2">
                            <div class="form-group">
                                <label id="lblImagem1" for="fname">Imagem</label>
                                <img id="previewImagem1" src="@Model.CaminhoImagem" class="img-fluid" alt="Imagem do Banner" />
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12 mb-5">
                            <label id="labelImage5" for="tag">Digite as Tags</label>
                            @Html.TextAreaFor(m => m.Tags, new { @class = "form-control", @rows = "5" })

                            @* <select class="form-select" name="tag" id="tag" data-placeholder="Digite a tag" multiple>
                                <option value="">-- Escolha as tags --</option>
                                @{
                                    var itens = ViewBag.Tags;

                                    if (itens != null)
                                    {
                                        var itensSelecionados = Model.TagsList;  // Itens que já estão selecionados

                                        foreach (var item in itens)
                                        {
                                            if (itensSelecionados == null)
                                            {
                                                <option value="@item.Value">@item.Text</option>
                                            }
                                            else
                                            {
                                                if (itensSelecionados.Any(x => x.Id.ToString() == item.Value))
                                                {
                                                    <option value="@item.Value" selected="selected">@item.Text</option>
                                                }
                                                else
                                                {
                                                    <option value="@item.Value">@item.Text</option>
                                                }
                                            }
                                        }
                                    }
                                }
                            </select> *@
                        </div>
                    </div>
                    <div class="form-footer pt-5 border-top d-flex justify-content-between">
                        <a href="@Url.Action("Index", "Tema")" class="btn btn-primary text-left">
                            <i class="mdi mdi-undo mr-1"></i> Voltar
                        </a>
                        <div>
                            <button type="submit" class="btn btn-success">Salvar</button>
                            <button type="button" class="btn btn-light ml-2" onclick="cancelar()">Cancelar</button>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

@section Scripts {

    <script>
        $(document).ready(function () {
            // $('#tag').select2({
            //     theme: "bootstrap-5",
            //     width: $(this).data('width') ? $(this).data('width') : $(this).hasClass('w-100') ? '100%' : 'style',
            //     placeholder: $(this).data('placeholder'),
            //     closeOnSelect: false,
            // });

            $('#formAdicionar').submit(function (e) {
                e.preventDefault(); // Evita o envio padrão do formulário

                var descricao = $("#texto").val();
                var titulo = $("#titulo").val();
                var fileInput = $("#fileInput").val();
                var tags = $("#tags").val();

                if (!descricao || !titulo || !fileInput || !tags) {
                    alert("Atenção!", "Verifique os campos se estão preenchidos.", "warning");
                    return;
                }

                // Se todos os campos estiverem preenchidos, envie o formulário
                this.submit(); // Aqui corrigimos para enviar o formulário corretamente
            });
        });

        function cancelar() {
            $("#texto").val("");
            $("#titulo").val("");
            $("#tags").val("");

            $('#fileInput').wrap('<form>').closest('form').get(0).reset();
            $('#fileInput').unwrap();

            var label = document.getElementById('lblImagem1');
            var preview = document.getElementById('previewImagem1');

            preview.src = '';
            preview.style.display = 'none';
            label.style.display = 'none';

            var preview = document.getElementById('previewImagem1');
        }


        function previewFile() {
            var status = document.getElementById('status1');
            // var label = document.getElementById('labelImage1')
            var preview = document.getElementById('previewImagem1');
            var fileInput = document.getElementById('fileInput').files[0];
            var reader = new FileReader();

         
            reader.onloadend = function () {
                //$("#imagem").attr('display', 'inline-block');
                preview.src = reader.result;
                preview.style.display = 'block';
                // label.style.display = 'block';
            }

            if (fileInput) {
                reader.readAsDataURL(fileInput);
            } else {
                preview.src = '';
                preview.style.display = 'none';
            }
        }

        document.getElementById('fileInput').addEventListener('change', previewFile);
    </script>
}

MHDecora.Admin/Views/Tema/Index.cshtml
@model List<MHDecora.Admin.Domain.Entities.Tema>

@{
    ViewBag.Title = "Banners";
    string titulo = TempData["Titulo"] as string;
    string mensagem = TempData["Mensagem"] as string;
    string tipoAlerta = TempData["TipoAlerta"] as string;
}

@if (!string.IsNullOrEmpty(mensagem))
{
    <div id="autoCloseAlert" class="alert alert-@tipoAlerta alert-dismissible fade show" role="alert">
        <strong>@titulo</strong> @mensagem
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
    </div>
}

<div id="msgAlert"></div>

<!-- Products Inventory -->
<div class="card card-default">
    <div class="card-header">
        <h2>Temas</h2>

        <a href="@Url.Action("Adicionar", "Tema")" class="btn btn-primary">
            <i class="mdi mdi-plus mr-1"></i> Adicionar
        </a>

    </div>
    <div class="card-body">
        <div class="collapse" id="collapse-data-tables">
            <pre class="language-html mb-4">

                </pre>
        </div>
        <table id="productsTable" class="table table-hover table-product" style="width:100%">
            <thead>
                <tr>
                    <th>Imagem</th>
                    <th>Titulo</th>
                    <th>Nome</th>
                    <th>Tag</th>
                    <th></th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>

                @{
                    if (Model.Count > 0)
                    {
                        foreach (var item in Model)
                        {
                            <tr>
                                <td class="py-0">
                                    <img src="@item.CaminhoImagem" style="margin-top: 8px;max-width: 85px;" alt="Product Image">
                                </td>
                                <td>@item.Titulo</td>
                                <td>@item.Texto</td>
                                <td>@item.Tags</td>
                                <td>
                                    <div class="dropdown">
                                        <a class="dropdown-toggle icon-burger-mini" href="#" role="button" id="dropdownMenuLink"
                                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" data-display="static">
                                        </a>

                                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuLink">
                                            <a class="dropdown-item" href="@Url.Action("Editar", "Tema", new { Id = @item.Id })">Editar</a>
                                            <a class="dropdown-item" data-toggle="modal" data-target="#modalApagar" onclick="setaID(@item.Id)" id="excluirTema" href="#">Excluir</a>
                                        </div>
                                    </div>
                                </td>
                                <td></td>
                                <td></td>
                            </tr>
                        }
                    }
                }

            </tbody>
        </table>

    </div>
</div>

@* Apagar *@
<div class="modal fade" id="modalApagar" tabindex="-1" role="dialog" aria-labelledby="modalApagarLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        @using (Html.BeginForm("Excluir", "Tema", FormMethod.Post, new { enctype = "multipart/form-data", id = "formExcluir" }))
        {
            <input type="hidden" value="" id="temaId" name="temaId">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="modalApagarLabel">Confirmar Exclusão</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">
                    Tem certeza que deseja excluir este tema?
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-danger" id="confirmarExclusao">Sim</button>
                    <button type="button" class="btn btn-light" data-dismiss="modal">Não</button>
                </div>
            </div>
        }
    </div>
</div>

@section Scripts {
    <script>
        function setaID(id) {
            $('#temaId').val(id);
        }
    </script>
}